intranetBundle\Entity\Entity\Users_F_Vacation:
    type: entity
    table: null
    repositoryClass: intranetBundle\Repository\Entity\Users_F_VacationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: '9'
        idForm:
            type: integer
            column: id_form
    lifecycleCallbacks: {  }
