intranetBundle\Entity\Entity\F_Vacation:
    type: entity
    table: null
    repositoryClass: intranetBundle\Repository\Entity\F_VacationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date1:
            type: string
            length: '10'
        date2:
            type: string
            length: '10'
        status:
            type: integer
            nullable: true
        isread:
            type: integer
            nullable: true
        type:
            type: string
            length: 8
        send:
            type: string
            length: '10'
    lifecycleCallbacks: {  }
